-- Pool Shed v1.9: grouped products and variants
-- Safe, additive migration. Existing products remain the stock-controlled records used by all order and stock foreign keys.
begin;

create table if not exists public.product_parents (
  id uuid primary key default gen_random_uuid(),
  parent_sku text not null unique,
  name text not null,
  brand text,
  category text,
  main_description text,
  product_type text not null default 'stock',
  featured boolean not null default false,
  default_image_url text,
  default_variant_id uuid,
  default_supplier_name text,
  active boolean not null default true,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products add column if not exists parent_product_id uuid;
alter table public.products add column if not exists variant_label text;
alter table public.products add column if not exists variant_name text;
alter table public.products add column if not exists variant_value text;
alter table public.products add column if not exists variant_sort_order integer not null default 0;
alter table public.products add column if not exists is_default_variant boolean not null default false;
alter table public.products add column if not exists pack_size text;
alter table public.products add column if not exists special_price numeric(12,2) not null default 0;
alter table public.products add column if not exists tax_status text not null default 'taxable';
alter table public.products add column if not exists condition text not null default 'new';
alter table public.products add column if not exists sales_account text;
alter table public.products add column if not exists purchase_account text;
alter table public.products add column if not exists stock_account text;
alter table public.products add column if not exists active boolean not null default true;
alter table public.products add column if not exists archived_at timestamptz;
alter table public.products add column if not exists updated_at timestamptz not null default now();

-- Add the FK only once and do not cascade-delete variants.
do $$ begin
  if not exists (select 1 from pg_constraint where conname='products_parent_product_id_fkey') then
    alter table public.products add constraint products_parent_product_id_fkey
      foreign key (parent_product_id) references public.product_parents(id) on delete restrict;
  end if;
end $$;

-- Backfill one parent for each existing standalone product. This keeps every existing product ID unchanged.
insert into public.product_parents(parent_sku,name,brand,category,main_description,product_type,featured,active,created_at,updated_at)
select p.sku,p.name,coalesce(nullif(p.supplier_name,''),'Unbranded'),p.category,p.internal_notes,'stock',false,true,p.created_at,now()
from public.products p
where p.parent_product_id is null
on conflict(parent_sku) do nothing;

update public.products p
set parent_product_id=pp.id,
    variant_label=coalesce(nullif(p.variant_label,''),'Default'),
    variant_name=coalesce(nullif(p.variant_name,''),'Option'),
    variant_value=coalesce(nullif(p.variant_value,''),'Default'),
    is_default_variant=true,
    updated_at=now()
from public.product_parents pp
where p.parent_product_id is null and pp.parent_sku=p.sku;

-- Preserve globally unique Pool Bros SKUs and barcodes. Supplier SKU is unique within a supplier.
create unique index if not exists products_sku_ci_unique on public.products(lower(sku));
create unique index if not exists products_barcode_ci_unique on public.products(lower(barcode)) where barcode is not null and btrim(barcode)<>'';
create unique index if not exists products_supplier_supplier_sku_ci_unique on public.products(lower(coalesce(supplier_name,'')),lower(supplier_sku)) where supplier_sku is not null and btrim(supplier_sku)<>'';
create index if not exists products_parent_product_idx on public.products(parent_product_id,variant_sort_order,id);
create index if not exists product_parents_search_idx on public.product_parents(lower(name),lower(parent_sku));

create table if not exists public.product_audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  action text not null,
  parent_product_id uuid references public.product_parents(id) on delete set null,
  variant_id uuid references public.products(id) on delete set null,
  previous_value jsonb,
  new_value jsonb,
  reason text,
  created_at timestamptz not null default now()
);
create index if not exists product_audit_parent_idx on public.product_audit_events(parent_product_id,created_at desc);
create index if not exists product_audit_variant_idx on public.product_audit_events(variant_id,created_at desc);

-- Validate a default variant belongs to the parent without creating a circular FK during backfill.
create or replace function public.validate_parent_default_variant()
returns trigger language plpgsql as $$
begin
  if new.default_variant_id is not null and not exists (
    select 1 from public.products p where p.id=new.default_variant_id and p.parent_product_id=new.id
  ) then raise exception 'Default variant must belong to the parent product'; end if;
  return new;
end $$;
drop trigger if exists trg_validate_parent_default_variant on public.product_parents;
create constraint trigger trg_validate_parent_default_variant
after insert or update of default_variant_id on public.product_parents
deferrable initially deferred for each row execute function public.validate_parent_default_variant();

-- Variant-level reporting view. All operational quantities remain keyed to products.id (the variant ID).
create or replace view public.product_variant_stock_summary as
select pp.id parent_product_id,pp.parent_sku,pp.name parent_name,p.id variant_id,p.variant_label,p.sku,p.supplier_name,p.supplier_sku,p.barcode,
       coalesce(sum(sb.qty_on_hand),0) physical_stock,
       coalesce(sum(sb.qty_allocated),0) allocated_stock,
       coalesce(sum(sb.qty_on_hand-sb.qty_allocated),0) available_stock,
       p.reorder_level,p.cost_price,p.trade_price,p.wholesale_price,p.special_price,p.rrp_price,p.active
from public.product_parents pp join public.products p on p.parent_product_id=pp.id
left join public.stock_balances sb on sb.product_id=p.id
group by pp.id,pp.parent_sku,pp.name,p.id,p.variant_label,p.sku,p.supplier_name,p.supplier_sku,p.barcode,p.reorder_level,p.cost_price,p.trade_price,p.wholesale_price,p.special_price,p.rrp_price,p.active;

alter table public.product_parents enable row level security;
alter table public.product_audit_events enable row level security;
drop policy if exists "authenticated read product parents" on public.product_parents;
create policy "authenticated read product parents" on public.product_parents for select to authenticated using(true);
drop policy if exists "authenticated manage product parents" on public.product_parents;
create policy "authenticated manage product parents" on public.product_parents for all to authenticated using(true) with check(true);
drop policy if exists "authenticated read product audit" on public.product_audit_events;
create policy "authenticated read product audit" on public.product_audit_events for select to authenticated using(true);
drop policy if exists "authenticated insert product audit" on public.product_audit_events;
create policy "authenticated insert product audit" on public.product_audit_events for insert to authenticated with check(user_id=auth.uid());

commit;

-- Rollback (schema only; run only after app rollback):
-- begin; drop view if exists public.product_variant_stock_summary; drop table if exists public.product_audit_events;
-- alter table public.products drop constraint if exists products_parent_product_id_fkey;
-- alter table public.products drop column if exists parent_product_id, drop column if exists variant_label,
-- drop column if exists variant_name, drop column if exists variant_value, drop column if exists variant_sort_order,
-- drop column if exists is_default_variant, drop column if exists pack_size, drop column if exists special_price,
-- drop column if exists tax_status, drop column if exists condition, drop column if exists sales_account,
-- drop column if exists purchase_account, drop column if exists stock_account, drop column if exists active,
-- drop column if exists archived_at, drop column if exists updated_at; drop table if exists public.product_parents; commit;

-- Pool Shed v1.9.2: controlled catalogue import batches and rollback audit
-- Additive only. Product rollback is performed by the application using stored before/after snapshots.
begin;

create table if not exists public.product_import_batches (
  id uuid primary key default gen_random_uuid(),
  file_name text,
  source text not null default 'csv',
  status text not null default 'completed' check (status in ('preview','completed','failed','undone')),
  uploaded_by uuid references auth.users(id) on delete set null,
  uploaded_at timestamptz not null default now(),
  total_rows integer not null default 0,
  created_rows integer not null default 0,
  updated_rows integer not null default 0,
  skipped_rows integer not null default 0,
  failed_rows integer not null default 0,
  error_report jsonb not null default '[]'::jsonb,
  undo_reason text,
  undone_by uuid references auth.users(id) on delete set null,
  undone_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.product_import_changes (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.product_import_batches(id) on delete restrict,
  variant_id uuid references public.products(id) on delete set null,
  sku text not null,
  change_type text not null check (change_type in ('created','updated','skipped','failed')),
  previous_value jsonb,
  new_value jsonb,
  created_at timestamptz not null default now()
);

create index if not exists product_import_batches_uploaded_at_idx on public.product_import_batches(uploaded_at desc);
create index if not exists product_import_changes_batch_idx on public.product_import_changes(batch_id,id);
create index if not exists product_import_changes_variant_idx on public.product_import_changes(variant_id);

alter table public.product_import_batches enable row level security;
alter table public.product_import_changes enable row level security;

-- Replace app_metadata role checks if your project uses a dedicated profiles/permissions table.
drop policy if exists "admin manage product import batches" on public.product_import_batches;
create policy "admin manage product import batches" on public.product_import_batches
for all to authenticated
using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role','') in ('Admin','Manager'))
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role','') in ('Admin','Manager'));

drop policy if exists "admin manage product import changes" on public.product_import_changes;
create policy "admin manage product import changes" on public.product_import_changes
for all to authenticated
using (coalesce(auth.jwt() -> 'app_metadata' ->> 'role','') in ('Admin','Manager'))
with check (coalesce(auth.jwt() -> 'app_metadata' ->> 'role','') in ('Admin','Manager'));

commit;

-- Rollback for v1.9.2 import governance tables only:
-- begin;
-- drop table if exists public.product_import_changes;
-- drop table if exists public.product_import_batches;
-- commit;
