import {randomUUID} from 'node:crypto';
import {db,eq} from './accounting.js';

const MAX_BYTES=26214400;
const ALLOWED=new Set(['image/jpeg','image/png','image/webp','application/pdf']);
const DOMAINS={
  product:{bucket:'product-media',table:'ps_product_media',prefix:'product-media:',entityColumn:'product_id',deletedColumn:'archived_at'},
  customer:{bucket:'customer-media',table:'ps_customer_media',prefix:'customer-media:',entityColumn:'customer_id',deletedColumn:'deleted_at'}
};
const PRODUCT_KINDS=new Set(['main_image','gallery','brochure','datasheet','installation_guide','warranty','certificate','other']);
const CUSTOMER_KINDS=new Set(['site_photo','drawing','survey','document','access','warranty','certificate','other']);
const cleanPart=v=>String(v||'').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,160)||'item';
const objectPath=p=>String(p||'').split('/').filter(Boolean).map(encodeURIComponent).join('/');
const headers=extra=>({apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY,...(extra||{})});
const absoluteSigned=value=>{const raw=String(value||'');if(!raw)return '';return /^https?:\/\//i.test(raw)?raw:String(process.env.SUPABASE_URL||'').replace(/\/$/,'')+(raw.startsWith('/')?'':'/')+raw};
const ext=m=>m==='image/png'?'png':m==='image/webp'?'webp':m==='application/pdf'?'pdf':'jpg';
export const isBusinessMediaRef=v=>/^(?:product|customer)-media:[0-9a-f-]{36}$/i.test(String(v||''));
export const mediaRef=(domain,id)=>DOMAINS[domain].prefix+id;
export function parseMediaRef(ref){for(const [domain,cfg] of Object.entries(DOMAINS))if(String(ref||'').startsWith(cfg.prefix))return {domain,id:String(ref).slice(cfg.prefix.length),...cfg};return null}
export function collectBusinessMediaRefs(value){const refs=new Set();(function walk(v){if(typeof v==='string'&&isBusinessMediaRef(v))refs.add(v);else if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object')Object.values(v).forEach(walk)})(value);return [...refs]}
async function signPath(bucket,path,expiresIn=3600){const r=await fetch(process.env.SUPABASE_URL+'/storage/v1/object/sign/'+bucket+'/'+objectPath(path),{method:'POST',signal:AbortSignal.timeout(12000),headers:headers({'Content-Type':'application/json'}),body:JSON.stringify({expiresIn})});if(!r.ok)throw Error('Secure media signing failed ('+r.status+')');const body=await r.json();return absoluteSigned(body.signedURL||body.signedUrl)}
async function uploadObject(bucket,path,mime,buffer){const r=await fetch(process.env.SUPABASE_URL+'/storage/v1/object/'+bucket+'/'+objectPath(path),{method:'POST',signal:AbortSignal.timeout(25000),headers:headers({'Content-Type':mime,'x-upsert':'false','Cache-Control':'3600'}),body:buffer});if(!r.ok)throw Object.assign(Error('Secure media upload failed ('+r.status+')'),{statusCode:502})}
function validate(domain,kind,mime,buffer){if(!DOMAINS[domain])throw Object.assign(Error('Unknown media domain'),{statusCode:400});if(!ALLOWED.has(mime))throw Object.assign(Error('Unsupported file type'),{statusCode:415});if(!buffer?.length||buffer.length>MAX_BYTES)throw Object.assign(Error('File must be between 1 byte and 25 MB'),{statusCode:413});const kinds=domain==='product'?PRODUCT_KINDS:CUSTOMER_KINDS;if(!kinds.has(kind))throw Object.assign(Error('Unsupported media category'),{statusCode:400})}
export async function uploadBusinessMedia({domain,workspaceId,entityId,userId,kind,fileName,mimeType,buffer,title='',altText='',notes='',siteKey=''}){validate(domain,kind,mimeType,buffer);const cfg=DOMAINS[domain],id=randomUUID(),suffix=ext(mimeType),storagePath=[workspaceId,cleanPart(entityId),id+'.'+suffix].map(cleanPart).join('/'),safeName=String(fileName||('file.'+suffix)).replace(/[\r\n]/g,' ').slice(0,180);await uploadObject(cfg.bucket,storagePath,mimeType,buffer);const row={id,workspace_id:workspaceId,[cfg.entityColumn]:entityId,asset_kind:kind,storage_path:storagePath,file_name:safeName,mime_type:mimeType,size_bytes:buffer.length,uploaded_by:userId};if(domain==='product'){row.title=String(title||'').slice(0,180);row.alt_text=String(altText||'').slice(0,240)}else{row.title=String(title||'').slice(0,180);row.notes=String(notes||'').slice(0,1000);row.site_key=String(siteKey||'').slice(0,120)}await db(cfg.table,{method:'POST',body:row});const previewUrl=await signPath(cfg.bucket,storagePath,3600);return {id,ref:mediaRef(domain,id),domain,entityId,kind,name:safeName,type:mimeType,size:buffer.length,title:row.title||'',altText:row.alt_text||'',notes:row.notes||'',siteKey:row.site_key||'',previewUrl}}
export async function listBusinessMedia({domain,workspaceId,entityId,includeArchived=false}){const cfg=DOMAINS[domain];if(!cfg)throw Object.assign(Error('Unknown media domain'),{statusCode:400});let path=cfg.table+'?workspace_id=eq.'+eq(workspaceId)+'&'+cfg.entityColumn+'=eq.'+eq(entityId)+'&select=*&order=created_at.desc';if(!includeArchived)path+='&'+cfg.deletedColumn+'=is.null';const rows=await db(path);return rows.map(r=>({...r,ref:mediaRef(domain,r.id)}))}
export async function signBusinessMedia(workspaceId,refs,expiresIn=3600,{allowArchivedProduct=true}={}){const parsed=[...new Set((refs||[]).filter(isBusinessMediaRef))].map(parseMediaRef).filter(Boolean).slice(0,150),out={};for(const domain of ['product','customer']){const cfg=DOMAINS[domain],ids=parsed.filter(x=>x.domain===domain).map(x=>x.id);if(!ids.length)continue;let path=cfg.table+'?workspace_id=eq.'+eq(workspaceId)+'&id=in.('+ids.join(',')+')&select=id,storage_path,'+cfg.deletedColumn;if(domain==='customer'||!allowArchivedProduct)path+='&'+cfg.deletedColumn+'=is.null';const rows=await db(path);await Promise.all(rows.map(async r=>{out[mediaRef(domain,r.id)]=await signPath(cfg.bucket,r.storage_path,expiresIn)}))}return out}
export async function archiveBusinessMedia({domain,workspaceId,id}){const cfg=DOMAINS[domain];if(!cfg)throw Object.assign(Error('Unknown media domain'),{statusCode:400});const stamp=new Date().toISOString();const body={[cfg.deletedColumn]:stamp};const rows=await db(cfg.table+'?workspace_id=eq.'+eq(workspaceId)+'&id=eq.'+eq(id),{method:'PATCH',body});return rows?.[0]||null}

export async function assertBusinessMediaRefs(workspaceId,payload){const refs=collectBusinessMediaRefs(payload);if(!refs.length)return true;const parsed=refs.map(parseMediaRef).filter(Boolean);const found=new Set();for(const domain of ['product','customer']){const cfg=DOMAINS[domain],ids=parsed.filter(x=>x.domain===domain).map(x=>x.id);if(!ids.length)continue;let path=cfg.table+'?workspace_id=eq.'+eq(workspaceId)+'&id=in.('+ids.join(',')+')&select=id,'+cfg.deletedColumn;if(domain==='customer')path+='&'+cfg.deletedColumn+'=is.null';const rows=await db(path);rows.forEach(r=>found.add(mediaRef(domain,r.id)))}const missing=refs.filter(r=>!found.has(r));if(missing.length)throw Object.assign(Error('One or more secure Product Hub / CRM files are no longer available. Replace the missing file before publishing.'),{statusCode:409});return true}
export async function resolveBusinessMedia(workspaceId,payload,expiresIn=1800){const copy=JSON.parse(JSON.stringify(payload)),refs=collectBusinessMediaRefs(copy);if(!refs.length)return copy;const urls=await signBusinessMedia(workspaceId,refs,expiresIn);(function walk(v){if(Array.isArray(v)){for(let i=0;i<v.length;i++){if(typeof v[i]==='string'&&isBusinessMediaRef(v[i]))v[i]=urls[v[i]]||'';else if(v[i]&&typeof v[i]==='object')walk(v[i])}return}if(v&&typeof v==='object')for(const k of Object.keys(v)){if(typeof v[k]==='string'&&isBusinessMediaRef(v[k]))v[k]=urls[v[k]]||'';else if(v[k]&&typeof v[k]==='object')walk(v[k])}})(copy);return copy}
