import {randomUUID,createHash} from 'node:crypto';
import {db,eq,xeroIntegrationReadiness} from './accounting.js';
import {resolveBusinessMedia} from './business-media.js';
const iso=()=>new Date().toISOString(),date=()=>iso().slice(0,10),money=n=>Number(Number(n||0).toFixed(2));
const clone=v=>JSON.parse(JSON.stringify(v));
export const tokenHash=t=>createHash('sha256').update(String(t||'')).digest('hex');
export const safeHash=t=>createHash('sha256').update(String(t||'')).digest('hex');
const QUOTE_MEDIA_BUCKET='quote-media';
const MEDIA_REF_PREFIX='quote-media:';
function storageObjectPath(path=''){return String(path).split('/').filter(Boolean).map(encodeURIComponent).join('/')}
function storageHeaders(extra={}){return {apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY,...extra}}
function normaliseSignedUrl(value){const raw=String(value||'');if(!raw)return '';return /^https?:\/\//i.test(raw)?raw:String(process.env.SUPABASE_URL||'').replace(/\/$/,'')+(raw.startsWith('/')?'':'/')+raw}
export function quoteMediaRef(id){return MEDIA_REF_PREFIX+String(id||'')}
export function quoteMediaIds(value){const found=new Set();(function walk(v){if(typeof v==='string'&&v.startsWith(MEDIA_REF_PREFIX)){const id=v.slice(MEDIA_REF_PREFIX.length);if(/^[0-9a-f-]{36}$/i.test(id))found.add(id);return}if(Array.isArray(v))return v.forEach(walk);if(v&&typeof v==='object')Object.values(v).forEach(walk)})(value);return [...found]}
async function signStoragePath(path,expiresIn=3600){const u=process.env.SUPABASE_URL+'/storage/v1/object/sign/'+QUOTE_MEDIA_BUCKET+'/'+storageObjectPath(path);const r=await fetch(u,{method:'POST',signal:AbortSignal.timeout(12000),headers:storageHeaders({'Content-Type':'application/json'}),body:JSON.stringify({expiresIn})});if(!r.ok)throw Error('Quote media signing failed ('+r.status+')');const body=await r.json();return normaliseSignedUrl(body.signedURL||body.signedUrl)}
export async function uploadQuoteMedia({workspaceId,quoteId,userId,fileName,mimeType,buffer}){const allowed=new Set(['image/jpeg','image/png','image/webp','application/pdf']);if(!allowed.has(mimeType))throw Object.assign(Error('Unsupported quote media type'),{statusCode:415});if(!buffer?.length||buffer.length>12582912)throw Object.assign(Error('Quote media must be between 1 byte and 12 MB'),{statusCode:413});const id=randomUUID(),ext=mimeType==='image/png'?'png':mimeType==='image/webp'?'webp':mimeType==='application/pdf'?'pdf':'jpg',safeName=String(fileName||('quote-media.'+ext)).replace(/[\r\n]/g,' ').slice(0,180),storagePath=[workspaceId,quoteId,id+'.'+ext].map(x=>String(x).replace(/[^a-zA-Z0-9._-]/g,'_')).join('/'),url=process.env.SUPABASE_URL+'/storage/v1/object/'+QUOTE_MEDIA_BUCKET+'/'+storageObjectPath(storagePath);const r=await fetch(url,{method:'POST',signal:AbortSignal.timeout(20000),headers:storageHeaders({'Content-Type':mimeType,'x-upsert':'false','Cache-Control':'3600'}),body:buffer});if(!r.ok)throw Object.assign(Error('Quote media upload failed ('+r.status+')'),{statusCode:502});await db('ps_quote_media',{method:'POST',body:{id,workspace_id:workspaceId,quote_id:quoteId,storage_path:storagePath,file_name:safeName,mime_type:mimeType,size_bytes:buffer.length,uploaded_by:userId}});const previewUrl=await signStoragePath(storagePath,3600);return {id,ref:quoteMediaRef(id),name:safeName,type:mimeType,size:buffer.length,storagePath,previewUrl}}
export async function signQuoteMedia(workspaceId,ids,expiresIn=3600){const wanted=[...new Set((ids||[]).filter(x=>/^[0-9a-f-]{36}$/i.test(String(x))))].slice(0,100);if(!wanted.length)return {};const rows=await db('ps_quote_media?workspace_id=eq.'+eq(workspaceId)+'&deleted_at=is.null&id=in.('+wanted.join(',')+')&select=id,storage_path');const out={};await Promise.all(rows.map(async row=>{out[row.id]=await signStoragePath(row.storage_path,expiresIn)}));return out}
export async function assertQuoteMediaRefs(workspaceId,payload){const ids=quoteMediaIds(payload);if(!ids.length)return true;const rows=await db('ps_quote_media?workspace_id=eq.'+eq(workspaceId)+'&deleted_at=is.null&id=in.('+ids.join(',')+')&select=id');const found=new Set(rows.map(x=>String(x.id)));const missing=ids.filter(id=>!found.has(id));if(missing.length)throw Object.assign(Error('One or more quote images are no longer available. Re-upload the missing media before publishing.'),{statusCode:409});return true}
export async function resolveQuoteMedia(workspaceId,payload,expiresIn=1800){let copy=clone(payload),ids=quoteMediaIds(copy);if(ids.length){const urls=await signQuoteMedia(workspaceId,ids,expiresIn);(function walk(v){if(Array.isArray(v)){for(let i=0;i<v.length;i++){const x=v[i];if(typeof x==='string'&&x.startsWith(MEDIA_REF_PREFIX)){const id=x.slice(MEDIA_REF_PREFIX.length);v[i]=urls[id]||''}else if(x&&typeof x==='object')walk(x)}return}if(v&&typeof v==='object')for(const k of Object.keys(v)){const x=v[k];if(typeof x==='string'&&x.startsWith(MEDIA_REF_PREFIX)){const id=x.slice(MEDIA_REF_PREFIX.length);v[k]=urls[id]||''}else if(x&&typeof x==='object')walk(x)}})(copy)}return resolveBusinessMedia(workspaceId,copy,expiresIn)}
export function selectedOptionIds(publicPayload,state={}){
 const selections=state.selections||{},out=new Set();
 for(const section of publicPayload.sections||[]){const allowed=new Set((section.options||[]).map(o=>o.id));let ids=Array.isArray(selections[section.id])?selections[section.id].filter(id=>allowed.has(id)):null;if(ids===null)ids=(section.options||[]).filter(o=>section.rule==='locked'||o.selected).map(o=>o.id);if(section.rule==='locked')ids=[...allowed];if(section.rule==='single'&&ids.length!==1)throw Error(section.title+': choose exactly one option');if(section.required&&section.rule!=='locked'&&!ids.length)throw Error(section.title+': a selection is required');if(section.rule==='optional'&&ids.length>1)throw Error(section.title+': choose at most one option');ids.forEach(id=>out.add(id))}return out;
}
export function acceptedLines(publicPayload,commercialPayload,state={}){const selected=selectedOptionIds(publicPayload,state),matrix=commercialPayload.operationalOptions||[];if(matrix.length)return matrix.filter(x=>selected.has(x.optionId)||x.rule==='locked').flatMap(x=>clone(x.lines||[]));return clone(commercialPayload.operationalLines||[])}
export function acceptedTotals(publicPayload,lines){const net=money(lines.reduce((s,l)=>s+Number(l.qty||0)*Number(l.unitPrice||0),0)),vat=money(net*Number(publicPayload.vatRate??20)/100),gross=money(net+vat),deposit=money(gross*Number(publicPayload.depositPercent||50)/100),cost=money(lines.filter(l=>l.bundleRole!=='head').reduce((s,l)=>s+Number(l.qty||0)*Number(l.unitCost||0),0));return {net,vat,gross,deposit,cost,profit:money(net-cost),margin:net?money((net-cost)/net*100):0}}
function nextId(list,prefix,start){const used=new Set((list||[]).map(x=>x.id));let n=start+(list||[]).length,id;do{id=prefix+'-'+n++}while(used.has(id));return id}
function nextJobId(d){return nextId(d.jobs,'J',1001)}
function productMap(d){return new Map((d.products||[]).map(p=>[String(p.id),p]))}
function allocate(d,line,soId,jobId){if(!line.productId||line.bundleRole==='head')return 0;let need=Number(line.qty||0),allocated=0;const rows=(d.stock||[]).filter(r=>String(r.productId)===String(line.productId)).sort((a,b)=>String(a.locationId).localeCompare(String(b.locationId)));for(const row of rows){if(need<=0)break;const free=Math.max(0,Number(row.qty||0)-Number(row.allocated||0)),take=Math.min(free,need);if(take<=0)continue;row.allocated=Number(row.allocated||0)+take;allocated+=take;need-=take;d.allocations=d.allocations||[];d.allocations.push({id:'A-'+(1001+d.allocations.length),jobId,productId:line.productId,qty:take,fromLocationId:row.locationId,status:'Allocated',salesOrderId:soId,source:'Quote Studio acceptance'});d.movements=d.movements||[];d.movements.push({id:'M-'+(9001+d.movements.length),type:'Allocation',productId:line.productId,qty:take,from:row.locationId,to:jobId||soId,ref:soId,user:'Quote Studio',date:date(),note:'Automatically allocated from accepted quote'})}return allocated}
function handoverPolicy(commercial={}){const workflow=commercial.workflow==='quick'?'quick':'project',quick=workflow==='quick',raw=commercial.handoverPolicy||{};return {workflow,createProjectOnAcceptance:raw.createProjectOnAcceptance==null?!quick:!!raw.createProjectOnAcceptance,createSalesOrderOnAcceptance:raw.createSalesOrderOnAcceptance!==false,allocateStockOnAcceptance:raw.allocateStockOnAcceptance!==false,createDraftPurchaseOrders:raw.createDraftPurchaseOrders!==false,xeroRequestMode:['none','full','deposit'].includes(raw.xeroRequestMode)?raw.xeroRequestMode:(quick?'full':'deposit'),requirePaymentBeforePORelease:raw.requirePaymentBeforePORelease!==false}}
function paymentInfo(publicPayload,commercial,totals){const hp=handoverPolicy(commercial),mode=hp.xeroRequestMode,amount=mode==='full'?totals.gross:mode==='deposit'?totals.deposit:0;return {...hp,mode,amount,label:mode==='full'?'Full payment':mode==='deposit'?'Deposit':'No automatic payment request',required:mode!=='none',gate:mode!=='none'&&hp.requirePaymentBeforePORelease}}
function confirmedCustomer(acceptance){const x=acceptance?.evidence?.customerConfirmation||{},a=x.address||{};return {name:String(x.name||acceptance?.signer||'').trim(),email:String(x.email||'').trim(),phone:String(x.phone||'').trim(),address:{line1:String(a.line1||'').trim(),line2:String(a.line2||'').trim(),city:String(a.city||'').trim(),county:String(a.county||'').trim(),postcode:String(a.postcode||'').trim(),country:String(a.country||'United Kingdom').trim()||'United Kingdom'}}}
function addressText(a){return [a?.line1,a?.line2,a?.city,a?.county,a?.postcode,a?.country].filter(Boolean).join(', ')}
export function convertSnapshot(snapshot,{publication,acceptance}){
 const d=clone(snapshot||{});for(const k of ['quotes','jobs','salesOrders','purchaseOrders','stock','allocations','movements','customers','products'])if(!Array.isArray(d[k]))d[k]=[];
 const publicPayload=publication.public_payload||{},commercial=publication.commercial_payload||{},quoteId=publication.quote_id,versionNumber=publication.version_number,hp=handoverPolicy(commercial);let q=d.quotes.find(x=>x.id===quoteId);if(!q){q={id:quoteId,customerId:commercial.customerId||'',projectName:publicPayload.projectName||quoteId,projectType:publicPayload.projectType||'Pool Project',workflow:hp.workflow,handoverPolicy:clone(commercial.handoverPolicy||{}),status:'Accepted',createdAt:publication.created_at||iso(),updatedAt:iso(),versions:[],deliveries:[],approvals:[],engagement:{events:[]},audit:[]};d.quotes.unshift(q)}q.workflow=hp.workflow;q.handoverPolicy=clone(commercial.handoverPolicy||q.handoverPolicy||{});q.versions=Array.isArray(q.versions)?q.versions:[];if(!q.versions.some(v=>Number(v.number)===Number(versionNumber)))q.versions.push({id:'QVER-'+publication.id,number:versionNumber,status:'Published',createdAt:publication.created_at,createdBy:publication.published_by,publicSnapshot:clone(publicPayload),commercialSnapshot:clone(commercial),hash:publication.version_hash});q.currentVersion=Math.max(Number(q.currentVersion||0),Number(versionNumber));q.publishedVersion=versionNumber;
 if(q.conversion?.salesOrderId){q.status='Accepted';q.acceptance=q.acceptance||acceptance;return {snapshot:d,conversion:q.conversion,alreadyConverted:true}}
 const lines=acceptedLines(publicPayload,commercial,publication.customer_state||{}),totals=acceptedTotals(publicPayload,lines),pay=paymentInfo(publicPayload,commercial,totals),products=productMap(d),createProject=hp.createProjectOnAcceptance,createSO=hp.createSalesOrderOnAcceptance,jobId=createProject?nextJobId(d):'',soId=createSO?nextId(d.salesOrders,'SO',2035):'',customerId=commercial.customerId||q.customerId||'',confirmed=confirmedCustomer(acceptance);let c=d.customers.find(x=>String(x.id)===String(customerId))||null;if(!c&&customerId){c={id:customerId,name:confirmed.name||publicPayload.customer?.name||'Customer',companyName:'',email:'',phone:'',mobile:'',addresses:{},status:'Active',tags:['Quote Studio']};d.customers.push(c)}if(c){const ca=confirmed.address||{};if(confirmed.name){c.name=confirmed.name;if(!c.companyName)c.companyName=confirmed.name}if(confirmed.email)c.email=confirmed.email;if(confirmed.phone){c.phone=confirmed.phone;if(!c.mobile)c.mobile=confirmed.phone}c.addresses=c.addresses||{};const addr={line1:ca.line1||'',line2:ca.line2||'',city:ca.city||'',county:ca.county||'',postcode:ca.postcode||'',country:ca.country||'United Kingdom',phone:confirmed.phone||c.phone||''};if(addr.line1||addr.postcode){c.addresses.primary=clone(addr);c.addresses.delivery=clone(addr);c.addresses.billing=c.addresses.billing&&c.addresses.billing.line1?c.addresses.billing:clone(addr);c.address=addressText(addr);c.deliveryAddress=addressText(addr);c.postcode=addr.postcode;c.city=addr.city;c.county=addr.county;c.country=addr.country}c.lastConfirmedAt=acceptance?.accepted_at||iso();c.lastConfirmedSource=quoteId+' v'+versionNumber}const depositPct=Number(publicPayload.depositPercent||commercial.depositPercent||50);let job=null;
 if(createProject){job={id:jobId,customerId,name:publicPayload.projectName||q.projectName||quoteId,status:pay.required?'Accepted / Payment Pending':'Accepted / Procurement',locationId:'',owner:commercial.ownerName||'Pool Bros',customerRef:quoteId+' v'+versionNumber,invoiceStage:pay.required?(pay.label+' pending'):'No payment gate',notes:'Created automatically from accepted '+quoteId+' v'+versionNumber,created:date(),createdBy:'Quote Studio',project:{version:2,quoteNet:totals.net,quoteRef:quoteId+' v'+versionNumber,quoteAccepted:true,targetMargin:Math.max(30,Number(commercial.minimumMargin||25)+5),minimumMargin:Number(commercial.minimumMargin||25),lossWarningMargin:5,remainingNet:0,billingMode:hp.workflow==='quick'?'single':'phases',invoiceExposureThresholdPct:40,invoiceExposureThresholdNet:0,variations:[],costs:[],phases:hp.workflow==='quick'?[{id:randomUUID(),name:pay.label,amountNet:pay.mode==='full'?totals.net:pay.mode==='deposit'?money(totals.net*depositPct/100):totals.net,due:date(),agreement:'Accepted '+quoteId+' v'+versionNumber,status:pay.required?'Ready':'Planned'}]:[{id:randomUUID(),name:'Deposit · Secure project',amountNet:money(totals.net*depositPct/100),due:date(),agreement:'Accepted '+quoteId+' v'+versionNumber,status:'Ready'},{id:randomUUID(),name:'Installation milestone',amountNet:money(totals.net*.4),due:'',agreement:'Raise at agreed installation stage',status:'Planned'},{id:randomUUID(),name:'Completion / handover',amountNet:money(totals.net*Math.max(0,100-depositPct-40)/100),due:'',agreement:'Raise at project handover',status:'Planned'}],tasks:[{id:randomUUID(),title:'Confirm job / project start window',status:'Open',owner:commercial.ownerName||''},{id:randomUUID(),title:'Review critical supplier lead times',status:'Open',owner:'Purchasing'}],documents:[],materialPlan:[],stockEvents:[],audit:[{at:iso(),user:'Quote Studio',action:'Project created from accepted quote',details:{quoteId,version:versionNumber,workflow:hp.workflow}}]}};d.jobs.push(job)}
 let so=null;if(createSO){so={id:soId,customerId,jobId:jobId||'',quoteRef:quoteId+' v'+versionNumber,xeroRef:pay.required?'Payment pending':'No payment gate',source:'Quote Studio',status:'New Order',tags:['Accepted Quote',hp.workflow==='quick'?'Quick Quote':'Project'],channel:'Quote Studio',priceList:'Accepted quote snapshot',priceOverrideReason:'Frozen accepted quote version',shipTo:c.deliveryAddress||c.address||'',created:date(),due:publicPayload.validUntil||'',carrier:createProject?'Project':'Quick Quote',lines:lines.map(l=>({productId:l.productId||'',qty:Number(l.qty||0),allocated:0,picked:0,packed:0,unitPrice:money(l.unitPrice||0),specialPrice:money(l.unitPrice||0),unitCost:money(l.unitCost||0),description:l.description||'',supplierSnapshot:l.supplier||'',supplierSku:l.supplierSku||'',skuSnapshot:l.sku||'',quoteLineId:l.id||'',quoteOptionId:l.quoteOptionId||'',lineType:l.lineType||'product',bundleRole:l.bundleRole||'',bundleInstanceId:l.bundleInstanceId||'',bundleParentId:l.bundleParentId||'',bundleParentSku:l.bundleParentSku||'',bundleParentName:l.bundleParentName||''}))};d.salesOrders.push(so);so.lines.forEach(line=>{line.allocated=hp.allocateStockOnAcceptance?allocate(d,line,soId,jobId):0;if(job&&line.productId&&line.bundleRole!=='head'){const prod=products.get(String(line.productId))||{};job.project.materialPlan.push({id:randomUUID(),productId:line.productId,plannedQty:Number(line.qty||0),budgetUnitCost:money(line.unitCost||prod.cost||0),note:'From '+quoteId+' v'+versionNumber+' · '+(line.description||'')})}})}
 const shortage=[];if(so&&hp.createDraftPurchaseOrders){for(const line of so.lines){if(!line.productId||line.bundleRole==='head')continue;const qty=Math.max(0,Number(line.qty||0)-Number(line.allocated||0));if(!qty)continue;const prod=products.get(String(line.productId))||{};shortage.push({line,qty,supplier:line.supplierSnapshot||prod.supplier||'Supplier to confirm',supplierSku:line.supplierSku||prod.supplierSku||'',unitCost:money(line.unitCost||prod.cost||0),leadTimeDays:Number(prod.leadTimeDays||0)})}}
 const grouped={};shortage.forEach(x=>(grouped[x.supplier]||(grouped[x.supplier]=[])).push(x));const poIds=[];for(const supplier of Object.keys(grouped)){const poId=nextId(d.purchaseOrders,'PO',1050);d.purchaseOrders.push({id:poId,supplier,status:'Draft - Review',due:publicPayload.validUntil||'',jobId:jobId||'',originalSalesOrderId:soId,source:'Accepted Quote Studio',reviewStatus:'Needs review',supplierEmailStatus:pay.gate?'Blocked until payment confirmed and reviewed':'Ready after purchasing review',customerId,customerName:c.name||c.companyName||'',customerShipTo:c.deliveryAddress||c.address||'',reviewNotes:'Created automatically from accepted '+quoteId+' v'+versionNumber+'. '+(pay.gate?'Release only after payment confirmation and purchasing review.':'Payment gate is not required; purchasing review still applies.'),depositGate:pay.gate?'Awaiting payment':'Not required',lines:grouped[supplier].map(x=>({productId:x.line.productId,qty:x.qty,received:0,salesOrderId:soId,salesOrderLineQty:x.line.qty,supplierSku:x.supplierSku,unitCost:x.unitCost,orderedDate:date(),dueDate:publicPayload.validUntil||'',leadTimeDays:x.leadTimeDays,chaseStatus:'Waiting',nextChaseDate:date(),supplierNotes:'Accepted quote demand · '+x.line.description}))});poIds.push(poId)}
 q.acceptance={id:acceptance.id,at:acceptance.accepted_at,version:versionNumber,status:'Accepted',signer:acceptance.signer,termsVersion:acceptance.terms_version,selections:clone(acceptance.selections||{}),customerConfirmation:clone(acceptance?.evidence?.customerConfirmation||{})};q.status='Accepted';q.updatedAt=iso();q.engagement=q.engagement||{};q.engagement.accepted=true;q.engagement.acceptanceStarted=true;q.conversion={createdAt:iso(),workflow:hp.workflow,projectId:jobId,salesOrderId:soId,purchaseOrderIds:poIds,deposit:{mode:pay.mode,label:pay.label,amount:pay.amount,status:pay.required?'Ready for Xero':'Not required',financeDocumentId:'',xeroNumber:'',lastCheckedAt:''},status:createProject?(pay.required?'Project created · payment pending':'Project created · procurement ready'):(pay.required?'Sales Order created · payment pending':'Sales Order created · procurement ready'),acceptedTotals:totals};q.audit=Array.isArray(q.audit)?q.audit:[];q.audit.unshift({id:randomUUID(),at:iso(),user:'Quote Studio',action:'Accepted quote converted',detail:{version:versionNumber,workflow:hp.workflow,projectId:jobId,salesOrderId:soId,purchaseOrderIds:poIds}});return {snapshot:d,conversion:q.conversion,alreadyConverted:false,totals,jobId,soId,poIds,quote:q};
}
export async function saveQuoteWorkspace(w,actor,expected,snapshot){const result=await db('rpc/ps_quote_workspace_save',{method:'POST',body:{w,actor,expected,snapshot}});if(!result)throw Object.assign(Error('The workspace changed while the customer was accepting. No data was overwritten; retry the acceptance.'),{statusCode:409});return result}
export async function tryQueueDeposit(w,publication,conversion,snapshot){const dep=conversion?.deposit||{},mode=dep.mode||publication.commercial_payload?.handoverPolicy?.xeroRequestMode||'deposit';if(mode==='none'||dep.status==='Not required')return {status:'Not required',reason:'Automatic Xero request is disabled for this quote'};const readiness=xeroIntegrationReadiness();const customer=(snapshot.customers||[]).find(c=>String(c.id)===String(publication.commercial_payload?.customerId||''));const contact=customer?.xeroContactId||customer?.xeroContactID||'';if(!readiness.liveEnabled)return {status:'Ready for Xero',reason:'Xero live connection is not enabled'};if(!contact)return {status:'Ready for Xero',reason:'Customer is not linked to a Xero ContactID'};const [connection]=await db('ps_finance_connections?workspace_id=eq.'+eq(w)+'&select=tenant_id');if(!connection?.tenant_id)return {status:'Ready for Xero',reason:'Xero organisation is not selected'};const members=await db('ps_finance_members?workspace_id=eq.'+eq(w)+'&role=in.(admin,accountant)&select=user_id,role&order=role.asc&limit=1');if(!members.length)return {status:'Ready for Xero',reason:'No finance admin/accountant is configured for automated queueing'};const totals=conversion.acceptedTotals||{},net=Number(totals.net||0),depositPct=Number(publication.public_payload?.depositPercent||50),netAmount=mode==='full'?net:money(net*depositPct/100),description=mode==='full'?'Payment for accepted quote':'Deposit to secure project',invoice={Type:'ACCREC',Contact:{ContactID:contact},Date:date(),DueDate:new Date(Date.now()+7*86400000).toISOString().slice(0,10),CurrencyCode:'GBP',LineAmountTypes:'Exclusive',Status:'DRAFT',LineItems:[{Description:description+' · '+publication.public_payload.projectName+' · '+publication.quote_id+' v'+publication.version_number,Quantity:1,UnitAmount:money(netAmount),AccountCode:'4000',TaxType:'OUTPUT2'}]};const source=(mode==='full'?'QUOTE-PAYMENT:':'QUOTE-DEPOSIT:')+publication.quote_id+':V'+publication.version_number,doc=randomUUID();const id=await db('rpc/ps_finance_enqueue',{method:'POST',body:{w,actor:members[0].user_id,doc,source,kind_value:'ACCREC',invoice}});return {status:'Queued to Xero',financeDocumentId:id,reason:'Automated after accepted quote conversion',mode}
}

// Normalised strokes are inert data, retained in the existing private acceptance evidence.
export function validateQuoteSignature(signature, termsAccepted) {
 if (termsAccepted !== true) throw Error('Please agree to the Terms & Conditions before signing.');
 if (!signature || typeof signature !== 'object') throw Error('Type or draw your signature before accepting.');
 if (signature.method === 'typed') {
  const text = typeof signature.text === 'string' ? signature.text.trim() : '';
  if (text.length < 2 || text.length > 200) throw Error('Type your signature using 2 to 200 characters.');
  return {version:1, method:'typed', text};
 }
 if (signature.method !== 'drawn' || !Array.isArray(signature.strokes) || !signature.strokes.length || signature.strokes.length > 100) throw Error('Draw your signature before accepting.');
 let count=0, distance=0;
 const strokes=signature.strokes.map(stroke=>{
  if (!Array.isArray(stroke) || !stroke.length) throw Error('Invalid signature stroke.');
  let last=null;
  return stroke.map(point=>{
   if (++count>3000 || !Array.isArray(point) || point.length!==2 || !point.every(n=>typeof n==='number' && Number.isFinite(n) && n>=0 && n<=1)) throw Error('Invalid or oversized signature. Clear the signature and try again.');
   const clean=point.map(n=>Math.round(n*10000)/10000);
   if(last) distance+=Math.hypot(clean[0]-last[0],clean[1]-last[1]);
   last=clean; return clean;
  });
 });
 if (distance<.01) throw Error('Draw your signature before accepting.');
 return {version:1,method:'drawn',coordinateSystem:'unit-square',strokes};
}
