/**
 * Canonical runtime CSS module order.
 *
 * Keep this as the single source of truth for both bundle generation and
 * architecture validation so a newly-added stylesheet cannot bypass checks.
 */
export const CSS_MODULES = Object.freeze([
  "system/00-color-tokens.css",
  "system/10-legacy-compat.css",
  "system/20-sales-product.css",
  "system/21-catalogue.css",
  "system/22-bundles.css",
  "system/23-platform-feature-overrides.css",
  "system/24-product-hub.css",
  "system/30-workspace-core.css",
  "system/31-project-workspace.css",
  "system/32-sales-workspace.css",
  "system/33-workspace-polish.css",
  "system/34-customer-workspace.css",
  "system/35-warehouse-workspace.css",
  "system/40-design-system.css",
  "system/41-sales-order-command.css",
  "system/42-sales-order-parity.css",
  "system/43-sales-order-finder-polish.css",
  "system/44-purchase-order-command.css",
  "system/45-project-360-command.css",
  "system/46-product-hub-command.css",
  "system/47-inventory-location-control.css",
  "system/48-fulfilment-command.css",
  "system/49-supplier-command.css",
  "system/50-finance-command.css",
  "system/51-analytics-command.css",
  "system/52-automation-command.css",
  "system/53-settings-command.css",
  "system/54-production-readiness.css",
  "system/55-login-command.css",
  "system/56-executive-premium-components.css",
  "system/57-notifications-command.css",
  "system/58-foundation-authority.css",
  "system/59-my-work-action-authority.css",
  "system/59-quote-studio.css",
  "system/60-responsive-layout.css",
  "system/61-project-design-parity.css",
  "system/62-record-controls.css",
  "system/63-workspace-compatibility.css",
  "system/64-project-reporting.css",
  "system/65-order-status-control.css",
]);
