from pathlib import Path
import json,re,sys,base64
from PIL import Image,ImageDraw
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]; PUBLIC=ROOT/'public'; ART=ROOT/'qa-v137'; ART.mkdir(exist_ok=True)
IMG=ART/'pool-hero.jpg'; im=Image.new('RGB',(1600,1000),(35,61,54)); d=ImageDraw.Draw(im); d.rectangle((120,170,1480,850),fill=(71,125,134)); d.rectangle((240,260,1360,760),fill=(124,177,184)); im.save(IMG,quality=90); data_url='data:image/jpeg;base64,'+base64.b64encode(IMG.read_bytes()).decode()
engine=(PUBLIC/'quote-studio-engine.js').read_text(); workspace=(PUBLIC/'quote-studio-workspace.js').read_text(); css=(PUBLIC/'assets/css/app.css').read_text()
html='''<!doctype html><html><head><meta charset="utf-8"><style>*{box-sizing:border-box}html,body{margin:0;font-family:Inter,Arial,sans-serif}.app{display:grid;grid-template-columns:238px 1fr;min-height:100vh}.sidebar{background:#111715;color:#fff;padding:20px}.main{min-width:0}.topbar{height:64px}.screen{min-height:100vh}'''+css+'''</style></head><body><div class="app"><aside class="sidebar">POOL SHED</aside><main class="main"><div class="topbar"></div><section id="screen-quotes" class="screen"></section></main></div><script>window.data={customers:[{id:'C1',name:'White Residence',email:'client@example.com'}],products:[{id:'P1',sku:'PB-COVER',supplierSku:'SUP-1',name:'Integrated Automatic Cover',category:'Covers',supplier:'Certikin',cost:5000,rrp:11800,image:'''+json.dumps(data_url)+'''},{id:'P2',sku:'PB-MANUAL',supplierSku:'SUP-2',name:'Manual Safety Cover',category:'Covers',supplier:'Certikin',cost:2100,rrp:5200,image:'''+json.dumps(data_url)+'''}],quotes:[],quoteTemplates:[],stock:[{productId:'P1',qty:1,allocated:0},{productId:'P2',qty:2,allocated:0}],jobs:[],salesOrders:[],purchaseOrders:[],allocations:[],movements:[],settings:{},users:[]};window.__POOL_SHED_GET_DATA__=()=>data;window.__POOL_SHED_SAVE_APP_DATA__=()=>true;window.__POOL_SHED_CURRENT_USER__=()=>({id:'U1',name:'Aaron'});window.__POOL_SHED_ACTIVE_SUBPAGE__=()=> 'Quotes';window.__POOL_SHED_WORKSPACE_ID__=()=> 'pool-bros-main';window.toast=()=>{};</script><script>'''+engine+'''</script><script>const q=PoolShedQuoteStudio.createQuote({customerId:'C1',projectName:'White Residence Pool Refurbishment',projectType:'Pool Refurbishment',workflow:'project'});const s=q.sections[0];s.title='Choose your pool cover';s.eyebrow='Curated choice';s.intro='Choose the cover that best suits the finished pool.';s.rule='single';PoolShedQuoteStudio.addProductOption(q.id,s.id,'P1',{selected:true,recommended:true});PoolShedQuoteStudio.addProductOption(q.id,s.id,'P2',{});window.__POOL_SHED_QUOTE_FOCUS__=q.id;</script><script>'''+workspace+'''</script><script>renderQuoteStudioWorkspace();</script></body></html>'''
errors=[]; results={}
with sync_playwright() as pw:
 b=pw.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox','--disable-dev-shm-usage']); p=b.new_page(viewport={'width':1920,'height':1080}); p.on('pageerror',lambda e: errors.append(str(e))); p.set_content(html,wait_until='load'); p.wait_for_timeout(250); p.locator('[data-qs-tab="Options & Packages"]').click(); p.wait_for_timeout(200)
 assert p.locator('.qs-builder-nav button').all_text_contents()==['Elements','Products','Sections','Uploads']
 initial=p.locator('.qs-canvas').evaluate('(e)=>e.getBoundingClientRect().width'); assert initial>900
 p.locator('[data-qs-action="focus-canvas"]').click(); p.wait_for_timeout(150); assert p.locator('.qs-builder.focus-canvas').count()==1; focus=p.locator('.qs-canvas').evaluate('(e)=>e.getBoundingClientRect().width'); assert focus>=initial
 p.screenshot(path=str(ART/'focus-canvas.png'),full_page=True)
 p.locator('[data-qs-action="focus-canvas"]').click(); p.locator('[data-qs-action="canvas-mobile"]').click(); p.wait_for_timeout(120); mw=p.locator('.qs-canvas').evaluate('(e)=>e.getBoundingClientRect().width'); assert 360<=mw<=410
 p.locator('[data-qs-action="canvas-desktop"]').click(); p.locator('[data-qs-action="zoom-in"]').click(); assert '110%' in p.locator('.qs-canvas-tools').inner_text()
 p.locator('[data-qs-action="toggle-builder-left"]').click(); assert p.locator('.qs-builder.left-collapsed').count()==1
 p.locator('[data-qs-action="toggle-builder-right"]').click(); assert p.locator('.qs-builder.right-collapsed').count()==1
 results={'DesignLabTabs':'PASS','InitialCanvasWidth':round(initial),'FocusCanvasWidth':round(focus),'MobileCanvasWidth':round(mw),'PanelCollapse':'PASS','RuntimeErrors':len(errors)}; b.close()
if errors: print(errors,file=sys.stderr); sys.exit(1)
print(json.dumps(results,indent=2))
