import {randomBytes,randomUUID} from 'node:crypto';
import {db,eq,audit} from '../server/accounting.js';
import {tokenHash,safeHash,selectedOptionIds,acceptedTotals,acceptedLines,convertSnapshot,saveQuoteWorkspace,tryQueueDeposit} from '../server/quote.js';
export const config={api:{bodyParser:false},maxDuration:60};
const send=(res,status,value)=>res.status(status).json(value);
async function rawBody(req,max=512000){let chunks=[],n=0;for await(const b of req){n+=b.length;if(n>max)throw Object.assign(Error('Request too large'),{statusCode:413});chunks.push(b)}return Buffer.concat(chunks).toString()}
async function identity(req,w,write=false){const auth=req.headers.authorization||'';if(!auth.startsWith('Bearer '))throw Object.assign(Error('Sign in first'),{statusCode:401});const r=await fetch(process.env.SUPABASE_URL+'/auth/v1/user',{headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:auth},signal:AbortSignal.timeout(10000)});if(!r.ok)throw Object.assign(Error('Sign in first'),{statusCode:401});const u=await r.json(),members=await db('ps_workspace_members?workspace_id=eq.'+eq(w)+'&user_id=eq.'+eq(u.id));if(!members.length||(write&&!['admin','operator'].includes(members[0].role)))throw Object.assign(Error('Quote Studio access denied'),{statusCode:403});return {...u,workspaceRole:members[0].role}}
async function publicationByToken(token){if(!token||token.length<20)throw Object.assign(Error('Invalid proposal link'),{statusCode:404});const rows=await db('ps_quote_publications?token_hash=eq.'+eq(tokenHash(token))+'&select=*');const p=rows[0];if(!p)throw Object.assign(Error('Proposal link not found'),{statusCode:404});if(p.status==='revoked')throw Object.assign(Error('This proposal link has been withdrawn'),{statusCode:410});if(p.expires_at&&Date.parse(p.expires_at)<Date.now()&&!p.accepted_at)throw Object.assign(Error('This proposal link has expired. Please contact Pool Bros for an updated version.'),{statusCode:410});return p}
function remoteMeta(req){const forwarded=String(req.headers['x-forwarded-for']||'').split(',')[0].trim();return {ipHash:forwarded?safeHash(forwarded).slice(0,24):'',userAgentHash:safeHash(req.headers['user-agent']||'').slice(0,24)}}
async function logEvent(p,type,detail,req){const meta=remoteMeta(req);await db('ps_quote_events',{method:'POST',body:{publication_id:p.id,event_type:String(type||'activity').slice(0,40),detail:detail&&typeof detail==='object'?detail:{},ip_hash:meta.ipHash,user_agent_hash:meta.userAgentHash}});return true}
function validateChoice(p,sectionId,selections){const s=(p.public_payload?.sections||[]).find(x=>x.id===sectionId);if(!s)throw Error('Proposal section not found');if(s.rule==='locked')throw Error('This specification is locked');const allowed=new Set((s.options||[]).map(o=>o.id));const ids=Array.isArray(selections)?[...new Set(selections.filter(x=>allowed.has(x)))]:[];if(s.rule==='single'&&ids.length!==1)throw Error('Choose exactly one option');if(s.rule==='optional'&&ids.length>1)throw Error('Choose at most one option');if(s.required&&!ids.length)throw Error('A selection is required');return ids}
async function updateCustomerState(p,patch){const next={...(p.customer_state||{}),...patch};await db('ps_quote_publications?id=eq.'+p.id,{method:'PATCH',body:{customer_state:next}});return next}
async function acceptanceConversion(p,acceptance){const [row]=await db('workspace_snapshots?workspace_id=eq.'+eq(p.workspace_id)+'&select=data,updated_at');if(!row?.data)throw Error('Pool Shed workspace is not ready for project conversion');const converted=convertSnapshot(row.data,{publication:p,acceptance}),saved=await saveQuoteWorkspace(p.workspace_id,p.published_by,row.updated_at,converted.snapshot);let xero={status:'Ready for Xero',reason:'Payment request has not been queued'};try{xero=await tryQueueDeposit(p.workspace_id,p,converted.conversion,converted.snapshot)}catch(e){xero={status:'Ready for Xero',reason:e.message||'Xero queue requires review'}};
 if(xero.financeDocumentId){const [latest]=await db('workspace_snapshots?workspace_id=eq.'+eq(p.workspace_id)+'&select=data,updated_at');if(latest?.data){const q=(latest.data.quotes||[]).find(x=>x.id===p.quote_id);if(q?.conversion?.deposit){q.conversion.deposit.status=xero.status;q.conversion.deposit.financeDocumentId=xero.financeDocumentId;q.conversion.deposit.queuedAt=new Date().toISOString();try{await saveQuoteWorkspace(p.workspace_id,p.published_by,latest.updated_at,latest.data)}catch(_){}}}}
 return {conversion:converted.conversion,xero,saved};}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');const origin=process.env.APP_ORIGIN||'http://localhost',url=new URL(req.url,origin),action=url.searchParams.get('action')||'public',w=url.searchParams.get('workspace')||'pool-bros-main',token=url.searchParams.get('token')||'';
 try{
  if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY)throw Object.assign(Error('Quote Studio secure backend is not configured'),{statusCode:503});
  if(action==='staff'){
   if(req.method!=='GET')return send(res,405,{error:'GET required'});const u=await identity(req,w,false),quoteId=String(url.searchParams.get('quoteId')||'').trim();let query='ps_quote_publications?workspace_id=eq.'+eq(w)+'&select=id,quote_id,version_number,status,expires_at,accepted_at,recipient_email,created_at,customer_state&order=created_at.desc&limit=250';if(quoteId)query+='&quote_id=eq.'+eq(quoteId);const publications=await db(query),ids=publications.map(x=>x.id);let events=[],messages=[],acceptances=[];if(ids.length){const list='in.('+ids.join(',')+')';[events,messages,acceptances]=await Promise.all([db('ps_quote_events?publication_id='+list+'&select=id,publication_id,event_type,detail,created_at&order=created_at.desc&limit=1000'),db('ps_quote_messages?publication_id='+list+'&select=id,publication_id,section_id,option_id,body,status,created_at,resolved_at&order=created_at.desc&limit=500'),db('ps_quote_acceptances?publication_id='+list+'&select=id,publication_id,quote_id,version_number,signer,terms_version,selections,accepted_at&order=accepted_at.desc&limit=250')]);}const financeDocuments=await db('ps_finance_documents?workspace_id=eq.'+eq(w)+'&source_id=like.'+eq('QUOTE-%')+'&select=id,source_id,xero_id,xero_number,status,amount_due,amount_paid,currency,checked_at,updated_at&order=created_at.desc&limit=250');return send(res,200,{publications,events,messages,acceptances,financeDocuments,user:u.id});
  }
  if(action==='publish'){
   if(req.method!=='POST')return send(res,405,{error:'POST required'});if(req.headers.origin&&req.headers.origin!==process.env.APP_ORIGIN)return send(res,403,{error:'Invalid origin'});const u=await identity(req,w,true),body=JSON.parse(await rawBody(req)||'{}'),version=body.version;if(!body.quoteId||!version?.publicSnapshot||!version?.commercialSnapshot)throw Error('Incomplete quote publication');if(JSON.stringify(version).length>1500000)throw Error('Published quote is too large');const days=Math.min(365,Math.max(1,Number(body.delivery?.expiryDays||30))),plain=randomBytes(32).toString('base64url'),id=randomUUID(),expires=new Date(Date.now()+days*86400000).toISOString();await db('ps_quote_publications',{method:'POST',body:{id,workspace_id:w,quote_id:String(body.quoteId).slice(0,80),version_number:Number(version.number),version_hash:String(version.hash||''),token_hash:tokenHash(plain),public_payload:version.publicSnapshot,commercial_payload:version.commercialSnapshot,customer_state:{selections:{}},published_by:u.id,recipient_name:String(body.delivery?.recipientName||'').slice(0,200),recipient_email:String(body.delivery?.recipientEmail||'').slice(0,320),permissions:String(body.delivery?.permissions||'standard').slice(0,50),expires_at:expires,status:'live'}});await audit(w,u.id,'quote_published',{quoteId:body.quoteId,version:version.number,publication:id});const clientUrl=(process.env.APP_ORIGIN||'').replace(/\/$/,'')+'/proposal?token='+encodeURIComponent(plain);return send(res,200,{publicationId:id,clientUrl,expiresAt:expires,deliveryStatus:'secure_link_ready'});
  }
  if(action==='public'){
   if(req.method!=='GET')return send(res,405,{error:'GET required'});const p=await publicationByToken(token);await logEvent(p,'open',{quoteId:p.quote_id,version:p.version_number},req);const state=p.customer_state||{};return send(res,200,{proposal:p.public_payload,publication:{id:p.id,quoteId:p.quote_id,version:p.version_number,status:p.status,expiresAt:p.expires_at,accepted:!!p.accepted_at},customerState:{selections:state.selections||{}}});
  }
  const p=await publicationByToken(token);
  if(action==='event'){
   if(req.method!=='POST')return send(res,405,{error:'POST required'});const body=JSON.parse(await rawBody(req,64000)||'{}'),allowed=new Set(['open','heartbeat','leave','section_view','document','option_change','question','acceptance','accepted']);if(!allowed.has(body.type))throw Error('Unsupported engagement event');await logEvent(p,body.type,{...(body.detail||{}),engagedSeconds:Math.min(86400,Math.max(0,Number(body.engagedSeconds||body.detail?.engagedSeconds||0)))},req);return send(res,200,{ok:true});
  }
  if(action==='choice'){
   if(req.method!=='POST')return send(res,405,{error:'POST required'});if(p.accepted_at)throw Error('This proposal has already been accepted');const body=JSON.parse(await rawBody(req,64000)||'{}'),ids=validateChoice(p,body.sectionId,body.selections),state=p.customer_state||{},selections={...(state.selections||{}),[body.sectionId]:ids};await updateCustomerState(p,{selections});await logEvent(p,'option_change',{sectionId:body.sectionId,selections:ids},req);return send(res,200,{ok:true,selections});
  }
  if(action==='question'){
   if(req.method!=='POST')return send(res,405,{error:'POST required'});const body=JSON.parse(await rawBody(req,16000)||'{}'),text=String(body.text||'').trim();if(!text||text.length>2000)throw Error('Enter a question under 2,000 characters');await db('ps_quote_messages',{method:'POST',body:{id:randomUUID(),publication_id:p.id,section_id:String(body.sectionId||'').slice(0,100),option_id:String(body.optionId||'').slice(0,100),body:text,status:'open'}});await logEvent(p,'question',{sectionId:body.sectionId||'',optionId:body.optionId||''},req);return send(res,200,{ok:true});
  }
  if(action==='accept'){
   if(req.method!=='POST')return send(res,405,{error:'POST required'});if(p.accepted_at){const existing=await db('ps_quote_acceptances?publication_id=eq.'+p.id+'&select=id,accepted_at');return send(res,200,{accepted:true,id:existing[0]?.id,acceptedAt:existing[0]?.accepted_at,alreadyAccepted:true})}const body=JSON.parse(await rawBody(req,128000)||'{}'),signer=String(body.signer||'').trim();if(signer.length<2||signer.length>200)throw Error('Enter the full name of the person accepting the proposal');if(String(body.termsVersion||'')!==String(p.public_payload?.termsVersion||''))throw Error('The Terms & Conditions version has changed. Refresh the proposal before accepting.');const state=p.customer_state||{},incoming=body.selections&&typeof body.selections==='object'?body.selections:{},merged={...(state.selections||{}),...incoming};selectedOptionIds(p.public_payload,{selections:merged});const lines=acceptedLines(p.public_payload,p.commercial_payload,{selections:merged}),totals=acceptedTotals(p.public_payload,lines),id=randomUUID(),meta=remoteMeta(req),evidence={quoteHash:p.version_hash,ipHash:meta.ipHash,userAgentHash:meta.userAgentHash,acceptedTotals:totals};const acceptance={id,publication_id:p.id,quote_id:p.quote_id,version_number:p.version_number,signer,terms_version:p.public_payload.termsVersion,selections:merged,evidence,accepted_at:new Date().toISOString()};let conversion;try{conversion=await acceptanceConversion({...p,customer_state:{...state,selections:merged}},acceptance)}catch(e){if(e.statusCode===409)throw e;throw Object.assign(Error('Your acceptance is safe, but Pool Shed could not complete the operational conversion. Please contact Pool Bros. No duplicate order was created. '+e.message),{statusCode:500})}await db('ps_quote_acceptances',{method:'POST',body:acceptance});await db('ps_quote_publications?id=eq.'+p.id,{method:'PATCH',body:{customer_state:{...state,selections:merged},status:'accepted',accepted_at:acceptance.accepted_at}});await logEvent(p,'accepted',{totals,workflow:conversion.conversion?.workflow||p.commercial_payload?.workflow||'project',projectId:conversion.conversion?.projectId||'',salesOrderId:conversion.conversion?.salesOrderId||''},req);await audit(p.workspace_id,'customer','quote_accepted',{quoteId:p.quote_id,version:p.version_number,publication:p.id,workflow:conversion.conversion?.workflow||p.commercial_payload?.workflow||'project',projectId:conversion.conversion?.projectId||'',salesOrderId:conversion.conversion?.salesOrderId||''});return send(res,200,{accepted:true,id,acceptedAt:acceptance.accepted_at,deposit:totals.deposit,conversion:{workflow:conversion.conversion?.workflow||p.commercial_payload?.workflow||'project',projectCreated:!!conversion.conversion?.projectId,salesOrderCreated:!!conversion.conversion?.salesOrderId,paymentStatus:conversion.xero?.status||'Ready for Xero'}});
  }
  return send(res,404,{error:'Unknown quote action'});
 }catch(e){return send(res,e.statusCode||400,{error:e.message||'Quote Studio request failed'})}
}
